### ISSUE TITLE
Sell Tab

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/Auctionator-TBC-2.4.3#1]
Hi, getting the following error after making a fresh character. Error occurs when click on the "Sell" tab. 
I haven't yet run a scan, so have no database (if that's at all relevant).

 ```
Interface\AddOns\Auctionator\Auctionator.lua:3196: attempt to index upvalue 'gAtr_ItemSlotInfo' (a nil value)
------------
VERS:3.0.0   MEM:   800 KB   DB:0   SE:1  SL:2  DCP:<nil>  DBVERS:4
------------
REALMS: , Netherwing_Alliance (0)
------------
STACK: Atr_UpdateUI_SellPane > Atr_UpdateUI > Atr_Idle > Atr_OnUpdate
------------
ADDONS: , Auctionator
```

**Comment by RichSteini** [comment]
Something i did not test, should be fixed now [Fix error after making a fresh character (itemslotinfo)](https://github.com/RichSteini/Auctionator-TBC-2.4.3/commit/1e0a169ef83605b733907134d2f56121343e7f9e).
