### ISSUE TITLE
Vendor Values are not shown

### ISSUE THREAD

**Issue by SilverSaw** [RichSteini/Auctionator-TBC-2.4.3#4]
Vendor Values are using code from wotlk and tables must be added. In wotlk vendor values are integrated into the item tooltip, in tbc they have to be taken from a table in the addon code. They are plenty of addons like VendorPrices, VendorValues or similar where this tabe could be taken from.

**Comment by RichSteini** [comment]
Fixed in [Fix itemprice tooltip](https://github.com/RichSteini/Auctionator-TBC-2.4.3/commit/0778ef38844de3a34b14eb1eeddb6bd7a7cd4a7c) .
